hosts:
  "localhost":
    listen:
      port: 80
    paths:
      "/":
        file.dir: /usr/local/share/doc/h2o

# user: nobody
access-log: /dev/stdout
error-log: /dev/stderr
# pid-file: /path/to/the/pid-file
